project:
  type: default
  render:
    - index.qmd

format:
  html:
    theme:
      light: lux
    number-sections: false
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    code-tools: false
    css: styles.css
